export const BOOKING_ADDED_REQUEST = 'BOOKING_ADDED_REQUEST'
export const BOOKING_ADDED_SUCCESS = 'BOOKING_ADDED_SUCESS'
export const BOOKING_ADDED_FAIL = 'BOOKING_ADDED_FAIL'

export const BOOKING_INFO_REQUEST = 'BOOKING_INFO_REQUEST'
export const BOOKING_INFO_SUCCESS = 'BOOKING_INFO_SUCESS'
export const BOOKING_INFO_FAIL = 'BOOKING_INFO_FAIL'

export const BOOKING_PAYMENT_REQUEST = 'BOOKING_PAYMENT_REQUEST'
export const BOOKING_PAYMENT_SUCCESS = 'BOOKING_PAYMENT_SUCESS'
export const BOOKING_PAYMENT_FAIL = 'BOOKING_PAYMENT_FAIL'
export const BOOKING_PAYMENT_CLEAN = 'BOOKING_PAYMENT_CLEAN'