export const CART_ADD_MOVIE = 'CART_ADD_MOVIE'
export const CART_REMOVE_MOVIE = 'CART_REMOVE_MOVIE'
export const CART_RECORD_MOVIE_THEATER = 'CART_RECORD_MOVIE_THEATER'
export const CART_RECORD_PAYMENT_METHOD = 'CART_RECORD_PAYMENT_METHOD'