export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const MOVIE_INFO_REQUEST = 'MOVIE_INFO_REQUEST'
export const MOVIE_INFO_SUCCESS = 'MOVIE_INFO_SUCCESS'
export const MOVIE_INFO_FAIL = 'MOVIE_INFO_FAIL'

export const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST'
export const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS'
export const MOVIE_DELETE_FAIL = 'MOVIE_DELETE_FAIL'

export const MOVIE_CREATE_SUCCESS = 'MOVIE_CREATE_SUCCESS'
export const MOVIE_ADD_SUCCESS = 'MOVIE_ADD_SUCCESS'
export const MOVIE_ADD_FAIL = 'MOVIE_ADD_FAIL'
